theme: minima
title: Bass
author: SarahHo
email: your-email@domain.com
description: I am learning bass.
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
